import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../chatgpt-auth';
import { getNativeSession,sameOrigin } from './auth/_auth';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export {json};
export async function context(request:Request){if(!sameOrigin(request))return {error:json({error:'Origem inválida.'},403)};if(!env.DB)return {error:json({error:'Banco de dados indisponível.'},503)};const native=await getNativeSession(request);if(native){const buyer=native.role==='buyer';const path=new URL(request.url).pathname;
if(buyer&&!((request.method==='GET'&&(path==='/api/store'||path==='/api/reports'||path==='/api/supplier-report'||path==='/api/purchasing'||path==='/api/purchasing/notifications'||/^\/api\/purchasing\/[^/]+\/(details|xml)$/.test(path)))||(request.method==='POST'&&(path==='/api/profile/password'||path==='/api/purchasing/notifications'||/^\/api\/purchasing\/[^/]+\/messages$/.test(path)))||(request.method==='PATCH'&&/^\/api\/purchasing\/[^/]+\/(entry|guidance|resolution)$/.test(path))))return {error:json({error:'Acesso de comprador limitado ao setor de Compras.'},403)};
const requested=request.headers.get('X-Agra-Store-ID')||(/^\/api\/purchasing\/[^/]+\/xml$/.test(path)?new URL(request.url).searchParams.get('storeId'):null);
const store=buyer?await env.DB.prepare(`SELECT b.permission,s.id,s.name,s.plan,s.paid_until AS paidUntil,s.blocked_at AS blockedAt,s.access_status AS accessStatus,s.created_at AS createdAt FROM buyer_stores b JOIN stores s ON s.id=b.store_id WHERE b.account_id=? AND b.status='active' ${requested?'AND s.id=?':"AND s.blocked_at IS NULL AND s.access_status='approved'"} ORDER BY CASE WHEN s.id=? THEN 0 ELSE 1 END,s.name LIMIT 1`).bind(native.accountId,...(requested?[requested]:[]),native.storeId).first<{permission:string,id:string,name:string,plan:string,paidUntil:string|null,blockedAt:string|null,accessStatus:string,createdAt:string}>():await env.DB.prepare('SELECT id,name,plan,paid_until AS paidUntil,blocked_at AS blockedAt,access_status AS accessStatus,created_at AS createdAt FROM stores WHERE id=?').bind(native.storeId).first<{id:string,name:string,plan:string,paidUntil:string|null,blockedAt:string|null,accessStatus:string,createdAt:string}>();
if(buyer&&!store&&!(path==='/api/store'||path==='/api/profile/password'))return {error:json({error:'Você não tem acesso a esta loja. Selecione uma loja autorizada.'},403)};
if(buyer&&store&&'permission'in store&&store.permission!=='operate'&&request.method!=='GET'&&path!=='/api/purchasing/notifications'&&path!=='/api/profile/password')return {error:json({error:'Seu acesso a esta loja permite apenas consulta. Peça ao gestor permissão para operar.'},403)};
if(store?.blockedAt)return {error:json({error:'Esta empresa está bloqueada. Entre em contato com o administrador.'},403)};
if(store&&store.accessStatus!=='approved'&&!(request.method==='GET'&&path==='/api/store'))return {error:json({error:store.accessStatus==='denied'?'Sua solicitação de acesso não foi autorizada.':'Sua solicitação está aguardando aprovação do gestor.',accessStatus:store.accessStatus},403)};
return {user:{userId:'native:'+native.accountId,email:native.email,displayName:buyer?(native.name||native.email):(store?.name||native.storeName),fullName:null},db:env.DB,store,authMode:'native' as const,role:buyer?'buyer' as const:'manager' as const}}const platformUser=await getChatGPTUser();if(platformUser){const store=await env.DB.prepare('SELECT id,name,plan,paid_until AS paidUntil,blocked_at AS blockedAt,access_status AS accessStatus,created_at AS createdAt FROM stores WHERE owner_id=?').bind(platformUser.userId).first<{id:string,name:string,plan:string,paidUntil:string|null,blockedAt:string|null,accessStatus:string,createdAt:string}>();if(store?.blockedAt)return {error:json({error:'Esta empresa está bloqueada. Entre em contato com o administrador.'},403)};if(store&&store.accessStatus!=='approved'&&!(request.method==='GET'&&new URL(request.url).pathname==='/api/store'))return {error:json({error:store.accessStatus==='denied'?'Sua solicitação de acesso não foi autorizada.':'Sua solicitação está aguardando aprovação do gestor.',accessStatus:store.accessStatus},403)};return {user:platformUser,db:env.DB,store,authMode:'chatgpt' as const,role:'manager' as const}}return {error:json({error:'Entre para continuar.'},401)};}
export function failure(e:unknown){console.error('Falha ao salvar conferência',e);return json({error:'Não foi possível salvar agora. Tente novamente.'},503)}

export function coverage(_store:{plan:string;paidUntil:string|null}){return null}
