'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Store={id:string;name:string;ownerEmail:string;plan:string;accessStatus:string;accessReviewedAt:string|null;cnpj:string;phone:string;paidUntil:string|null;blockedAt:string|null;createdAt:string;invoiceCount:number;lastActivity:string|null};
type Payment={id:string;storeId:string;storeName:string;amountCents:number;paidAt:string;coverageUntil:string;method:string;reference:string;note:string};
type Report={summary:{stores:number;invoices:number;active:number;blocked:number;pending:number;receivedCents:number};stores:Store[];payments:Payment[];onlinePayments:Payment[];billing:{provider:string;updatedAt:string}|null};
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
const date=(d:string|null)=>d?new Date(d.length===10?d+'T12:00:00':d).toLocaleDateString('pt-BR'):'—';
async function api(url:string,options?:RequestInit){const r=await fetch(url,{...options,cache:'no-store',headers:{'Content-Type':'application/json',...options?.headers}});const value:any=await r.json();if(!r.ok)throw Error(value.error||'Não foi possível concluir.');return value}
export default function Admin(){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 const [storeId,setStoreId]=useState(''),[amount,setAmount]=useState('49.99'),[paidAt,setPaidAt]=useState(new Date().toISOString().slice(0,10)),[until,setUntil]=useState(''),[method,setMethod]=useState('Pix'),[reference,setReference]=useState(''),[note,setNote]=useState('');
 const [deleting,setDeleting]=useState<Store|null>(null),[confirmation,setConfirmation]=useState('');
 const [mail,setMail]=useState<{configured:boolean;sender:string}|null>(null),[mailKey,setMailKey]=useState(''),[mailSender,setMailSender]=useState(''),[mailBusy,setMailBusy]=useState(false);
 async function load(){try{const data=await api('/api/admin');setReport(data);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load();api('/api/admin/email').then(data=>{setMail(data);setMailSender(data.sender||'')}).catch(e=>setError(e.message));const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},15000);return()=>clearInterval(timer)},[]);
 async function saveMail(e:React.FormEvent){e.preventDefault();setMailBusy(true);setError('');try{const data=await api('/api/admin/email',{method:'POST',body:JSON.stringify({apiKey:mailKey,sender:mailSender})});setMail(data);setMailKey('');setSuccess('Envio de recuperação configurado. Verifique o domínio no serviço de e-mail antes de usar.')}catch(e){setError((e as Error).message)}finally{setMailBusy(false)}}
 async function act(work:()=>Promise<void>,message:string){setBusy(true);setError('');setSuccess('');try{await work();await load();setSuccess(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function savePayment(e:React.FormEvent){e.preventDefault();await act(async()=>{await api('/api/admin/payments',{method:'POST',body:JSON.stringify({storeId,amount:Number(amount.replace(',','.')),paidAt,coverageUntil:until,method,reference,note})});setReference('');setNote('')},'Recebimento registrado.')}
 function review(s:Store,accessStatus:'approved'|'denied'){act(async()=>{await api('/api/admin/stores/'+encodeURIComponent(s.id),{method:'PATCH',body:JSON.stringify({accessStatus})})},accessStatus==='approved'?'Acesso autorizado. O usuário já pode entrar no sistema.':'Solicitação não autorizada.')}
 function toggle(s:Store){act(async()=>{await api('/api/admin/stores/'+encodeURIComponent(s.id),{method:'PATCH',body:JSON.stringify({blocked:!s.blockedAt})})},s.blockedAt?'Acesso da empresa liberado.':'Empresa bloqueada e sessões encerradas.')}
 function remove(){if(!deleting)return;const s=deleting;act(async()=>{await api('/api/admin/stores/'+encodeURIComponent(s.id),{method:'DELETE',body:JSON.stringify({confirmation})});setDeleting(null);setConfirmation('')},'Cadastro e dados da empresa excluídos.')}
 return <>
  <div className="pagehead"><div><div className="eyebrow">ACESSO DO PROPRIETÁRIO</div><h1>Gestão do AGRA</h1><p>Empresas, acessos e recebimentos em um só lugar.</p></div></div>
  {error&&<div className="notice bad" role="alert">{error}</div>}{success&&<div className="notice good" role="status">{success}</div>}
  {!report?<div className="panel admin-loading">Carregando dados de gestão...</div>:<>
   <div className="metrics admin-metrics"><div className="metric"><span>Empresas cadastradas</span><b>{report.summary.stores}</b></div><div className="metric"><span>Notas conferidas</span><b>{report.summary.invoices}</b></div><div className="metric"><span>Empresas bloqueadas</span><b>{report.summary.blocked}</b></div><div className="metric"><span>Aguardando aprovação</span><b>{report.summary.pending}</b></div></div>
   <section className="panel reports-panel"><div className="eyebrow">SOLICITAÇÕES DE ACESSO</div><h2>Aguardando sua aprovação</h2><p>Novas empresas só podem usar o sistema depois da sua autorização.</p>{report.stores.filter(s=>s.accessStatus==='pending').map(s=><div className="payment-row" key={s.id}><div><b>{s.name}</b><small>{s.ownerEmail}</small><small>{s.cnpj?'CNPJ: '+s.cnpj:'CNPJ não informado'} · {s.phone?'Telefone: '+s.phone:'Telefone não informado'}</small><small>Solicitado em {date(s.createdAt)}</small></div><div className="admin-row-actions"><Button disabled={busy} onClick={()=>review(s,'approved')}>Aprovar acesso</Button><Button variant="outline" disabled={busy} onClick={()=>review(s,'denied')}>Recusar</Button></div></div>)}{!report.stores.some(s=>s.accessStatus==='pending')&&<p>Nenhuma solicitação pendente.</p>}</section>
   <section className="panel admin-billing"><div><div className="eyebrow">RECUPERAÇÃO DE SENHA</div><h2>Envio por e-mail</h2><p>{mail?.configured?'Credencial de envio cadastrada. Remetente: '+mail.sender:'Configure o envio para que usuários recuperem a senha pelo próprio e-mail.'}</p><p>Verifique um domínio no Resend e gere uma chave de API com permissão de envio. Insira os dados abaixo; a chave ficará protegida e não será exibida novamente.</p><form className="admin-test-config" onSubmit={saveMail}><label htmlFor="mail-sender">Remetente verificado</label><Input id="mail-sender" type="text" value={mailSender} onChange={e=>setMailSender(e.target.value)} placeholder="AGRA <acesso@seu-dominio.com>" required/><label htmlFor="mail-key">Chave de API do Resend</label><Input id="mail-key" type="password" autoComplete="off" value={mailKey} onChange={e=>setMailKey(e.target.value)} required/><Button type="submit" disabled={mailBusy||!mailKey||!mailSender}>Salvar envio de e-mail</Button></form></div></section>
   <div className="section-row"><div><h2>Empresas</h2><p>Bloqueie o acesso, libere novamente ou exclua um cadastro.</p></div></div>
   <div className="panel table-panel"><table className="admin-table"><thead><tr><th>Empresa</th><th>Cadastro</th><th>Notas</th><th>Última atividade</th><th>Decisão de acesso</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{report.stores.map(s=>{const active=s.accessStatus==='approved';const own=s.ownerEmail.toLowerCase()==='nandoagra362@gmail.com';return <tr key={s.id}><td><strong>{s.name}</strong><small>{s.ownerEmail||'E-mail não registrado'}</small></td><td>{date(s.createdAt)}</td><td>{s.invoiceCount}</td><td>{date(s.lastActivity)}</td><td>{s.accessStatus==='pending'?'Aguardando análise':s.accessReviewedAt?date(s.accessReviewedAt):'Acesso anterior'}</td><td><span className={'badge '+(s.blockedAt||s.accessStatus==='denied'?'surplus':active?'complete':'short')}>{s.blockedAt?'Bloqueada':active?'Autorizada':s.accessStatus==='denied'?'Não autorizada':'Aguardando aprovação'}</span></td><td><div className="admin-row-actions">{!own&&<>{s.accessStatus!=='approved'&&<Button size="sm" disabled={busy} onClick={()=>review(s,'approved')}>Aprovar</Button>}{s.accessStatus==='pending'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>review(s,'denied')}>Recusar</Button>}<Button size="sm" variant="outline" disabled={busy} onClick={()=>toggle(s)}>{s.blockedAt?'Desbloquear':'Bloquear'}</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>{setDeleting(s);setConfirmation('')}}>Excluir</Button></>}{own&&<small>Sua conta</small>}</div></td></tr>})}{!report.stores.length&&<tr><td colSpan={7}>Nenhuma empresa cadastrada.</td></tr>}</tbody></table></div>
   {deleting&&<section className="panel admin-delete" role="alertdialog" aria-modal="true" aria-label="Confirmar exclusão"><h2>Excluir {deleting.name}?</h2><p>Essa ação apaga definitivamente o cadastro, todas as notas, leituras e registros de pagamento da empresa. Digite o nome exato para confirmar.</p><label htmlFor="delete-confirmation">Nome da empresa</label><Input id="delete-confirmation" value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/><div className="admin-actions"><Button variant="destructive" disabled={busy||confirmation!==deleting.name} onClick={remove}>Excluir definitivamente</Button><Button variant="outline" onClick={()=>setDeleting(null)}>Cancelar</Button></div></section>}
   <div className="admin-grid"><section className="panel admin-form"><div className="eyebrow">CONTROLE MANUAL</div><h2>Registrar pagamento recebido</h2><p>Registre somente após confirmar o recebimento fora do AGRA.</p><form onSubmit={savePayment}><label>Empresa</label><select value={storeId} required onChange={e=>setStoreId(e.target.value)}><option value="">Selecione a empresa</option>{report.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="form-pair"><div><label>Valor (R$)</label><Input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><label>Forma</label><select value={method} onChange={e=>setMethod(e.target.value)}>{['Pix','Boleto','Cartão','Transferência','Dinheiro','Outro'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="form-pair"><div><label>Recebido em</label><Input type="date" required value={paidAt} onChange={e=>setPaidAt(e.target.value)}/></div><div><label>Cobertura até</label><Input type="date" required min={paidAt} value={until} onChange={e=>setUntil(e.target.value)}/></div></div><label>Referência / comprovante</label><Input value={reference} maxLength={100} onChange={e=>setReference(e.target.value)} placeholder="ID da transação (opcional)"/><label>Observação</label><Input value={note} maxLength={300} onChange={e=>setNote(e.target.value)} placeholder="Anotação interna (opcional)"/><Button type="submit" disabled={busy||!storeId||!until} className="action-full">Registrar recebimento</Button></form></section><section className="panel admin-payments"><div className="eyebrow">HISTÓRICO FINANCEIRO</div><h2>Recebimentos lançados</h2>{(report.payments.length||report.onlinePayments?.length)?[...report.payments,...(report.onlinePayments||[])].map(p=><div className="payment-row" key={p.id}><div><b>{p.storeName}</b><small>{date(p.paidAt)} · {p.method} · cobertura até {date(p.coverageUntil)}</small>{p.reference&&<small>Referência: {p.reference}</small>}</div><strong>{money(p.amountCents)}</strong></div>):<p>Nenhum pagamento registrado.</p>}</section></div>
  </>}
 </>
}
