'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {api} from '@/lib/client-api';
import SupplierReport from './supplier-report';
import BuyerReports from './buyer-reports';
import Purchasing from './purchasing';
import PasswordSettings from './password-settings';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
type StoreAccess={id:string;name:string;status:'active'|'pending';invitedBy:string;permission:'view'|'operate'};
function storeStyle(id:string):CSSProperties{let hash=0;for(const char of id)hash=(hash*31+char.charCodeAt(0))>>>0;const hue=hash%360;return {'--store-color':`hsl(${hue} 55% 34%)`,'--store-tint':`hsl(${hue} 55% 94%)`} as CSSProperties}
type Menu='reports'|'received'|'entered'|'purchasing'|'suppliers';
const menus:Record<Menu,string>={received:'Notas recebidas',reports:'Notas em conferência',entered:'Notas com entrada',purchasing:'Notas com divergência',suppliers:'Histórico por fornecedor'};
export default function BuyerPortal({email,logout}:{email:string;logout:()=>Promise<void>}){
 const [buyerName,setBuyerName]=useState(''),[nameDraft,setNameDraft]=useState(''),[nameLoaded,setNameLoaded]=useState(false);
 const [stores,setStores]=useState<StoreAccess[]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false);
 useEffect(()=>{api('/api/profile/buyer-name').then(data=>{setBuyerName(data.name);setNameDraft(data.name)}).catch(e=>setError(e.message)).finally(()=>setNameLoaded(true))},[]);
 async function saveName(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('/api/profile/buyer-name',{method:'PATCH',body:JSON.stringify({name:nameDraft})});setBuyerName(result.name);setNameDraft(result.name)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function refresh(){try{const data=await api('/api/buyer-stores');setStores(data.stores);setSelected(current=>data.stores.some((s:StoreAccess)=>s.id===current&&s.status==='active')?current:data.stores.find((s:StoreAccess)=>s.status==='active')?.id||null);setError('')}catch(e){setError((e as Error).message)}finally{setLoaded(true)}}
 useEffect(()=>{let mounted=true;const update=()=>{if(mounted&&document.visibilityState==='visible')refresh()};refresh();window.addEventListener('focus',update);const timer=setInterval(update,30000);return()=>{mounted=false;clearInterval(timer);window.removeEventListener('focus',update)}},[]);
 async function invitation(storeId:string,accept:boolean){setBusy(true);try{await api('/api/buyer-stores',{method:'POST',body:JSON.stringify({storeId,accept})});await refresh();if(accept){setSelected(storeId);setSettings(false)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const active=stores.filter(s=>s.status==='active'),pending=stores.filter(s=>s.status==='pending'),store=active.find(s=>s.id===selected);
 return <div className="shell"><aside className="sidebar"><div className="brand"><img src="/agra-identidade.png" alt="AGRA — Gestão de Recebimento"/></div><nav aria-label="Lojas de Compras"><div className="buyer-store-label">MINHAS LOJAS</div>{active.map(s=><button key={s.id} style={storeStyle(s.id)} className={s.id===selected&&!settings?'selected':''} onClick={()=>{setSelected(s.id);setSettings(false)}}><span className="store-color-dot"/><span>{s.name}</span></button>)}<button className={settings?'selected':''} onClick={()=>setSettings(true)}>Meu perfil</button></nav><div className="sidebar-bottom"><div className="store-name"><b>{buyerName||'Compras'}</b><small>{email}</small></div></div></aside><div className="body"><header className="topbar"><div className="crumb">Compras <span>/</span> <strong style={store?storeStyle(store.id):undefined} className="store-header-name">{settings?'Minha conta':store?.name||'Selecione uma loja'}</strong></div><div className="admin-actions"><span>{buyerName||email}</span><Button variant="outline" onClick={logout}>Sair</Button></div></header><main className="content">{error&&<p className="notice bad" role="alert">{error}</p>}{nameLoaded&&(settings||!buyerName)&&<section className="panel profile-card"><h2>{buyerName?'Meu nome':'Como você se chama?'}</h2><p>Seu nome identifica suas próximas ações nas notas de todas as lojas vinculadas à sua conta.</p><form className="admin-test-config" onSubmit={saveName}><label htmlFor="buyer-own-name">Nome do comprador</label><Input id="buyer-own-name" value={nameDraft} onChange={e=>setNameDraft(e.target.value)} required minLength={2} maxLength={100}/><Button disabled={busy||nameDraft.trim().length<2} type="submit">Salvar nome</Button></form></section>}{pending.length>0&&<section className="panel reports-panel buyer-invitations"><h2>Convites de lojas</h2><p>Aceite para consultar as notas desta loja com sua conta atual.</p>{pending.map(s=><div className="payment-row" key={s.id}><div><b>{s.name}</b><small>Convidado por {s.invitedBy} · {s.permission==='view'?'Somente consultar':'Consultar e operar'}</small></div><div className="admin-actions"><Button disabled={busy} onClick={()=>invitation(s.id,true)}>Aceitar loja</Button><Button disabled={busy} variant="outline" onClick={()=>invitation(s.id,false)}>Recusar</Button></div></div>)}</section>}{!loaded?<p>Carregando lojas...</p>:settings?<PasswordSettings email={email}/>:store?<StorePurchasing key={store.id+store.permission} store={store}/>:<section className="panel reports-panel"><h2>Nenhuma loja disponível</h2><p>Peça ao responsável pela loja para convidar seu e-mail em Meu perfil → Equipe → Acesso dos compradores.</p></section>}</main></div></div>
}
function StorePurchasing({store}:{store:StoreAccess}){
 const [menu,setMenu]=useState<Menu>('reports'),[counts,setCounts]=useState<Record<Menu,number>>({reports:0,received:0,entered:0,purchasing:0,suppliers:0});
 useEffect(()=>{let active=true;let pending=false;async function refresh(){if(pending||document.visibilityState!=='visible')return;pending=true;try{const data=await api('/api/purchasing/notifications',undefined,store.id);if(active)setCounts({reports:data.reportsCount||0,received:data.receivedCount||0,entered:data.enteredCount||0,purchasing:data.count||0,suppliers:0})}catch{}finally{pending=false}}refresh();const timer=setInterval(refresh,10000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh)}},[store.id]);
 async function read(selected:Menu='purchasing',seenAt?:string){await api('/api/purchasing/notifications',{method:'POST',body:JSON.stringify({menu:selected,seenAt})},store.id);setCounts(current=>({...current,[selected]:0}))}
 return <><section className="buyer-store-banner" style={storeStyle(store.id)}><strong>Loja selecionada: {store.name}</strong><span>{store.permission==='view'?'Acesso: somente consulta':'Acesso: consultar e operar'}</span></section><nav className="buyer-store-menus" aria-label={'Menus de '+store.name}>{(Object.entries(menus) as [Menu,string][]).map(([key,label])=><button key={key} className={menu===key?'selected':''} onClick={()=>setMenu(key)}>{label}{counts[key]>0&&<span className="menu-alert" aria-label={`${counts[key]} atualizações`}/>}</button>)}</nav>{menu==='suppliers'?<SupplierReport storeId={store.id} storeName={store.name}/>:menu==='purchasing'?<Purchasing key={menu} buyer storeId={store.id} storeName={store.name} canOperate={store.permission!=='view'} onRead={read}/>:<BuyerReports key={menu} storeId={store.id} storeName={store.name} canOperate={store.permission!=='view'} entered={menu==='entered'} received={menu==='received'} onRead={read} onEntered={()=>setMenu('entered')}/>}</>
}
