import { sqliteTable, text, integer, real, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const stores=sqliteTable('stores',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),ownerEmail:text('owner_email').notNull().default(''),cnpj:text('cnpj').notNull().default(''),phone:text('phone').notNull().default(''),profileName:text('profile_name').notNull().default(''),profilePhotoKey:text('profile_photo_key'),paidUntil:text('paid_until'),blockedAt:text('blocked_at'),createdAt:text('created_at').notNull(),plan:text('plan').notNull().default('piloto'),accessStatus:text('access_status').notNull().default('approved'),accessReviewedAt:text('access_reviewed_at'),accessReviewedBy:text('access_reviewed_by')},t=>[uniqueIndex('stores_owner_unique').on(t.ownerId)]);
export const invoices=sqliteTable('invoices',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),number:text('number').notNull(),supplier:text('supplier').notNull(),checkerName:text('checker_name').notNull().default(''),accessKey:text('access_key'),xmlKey:text('xml_key'),purchasingEntry:integer('purchasing_entry'),entryUpdatedAt:text('entry_updated_at'),purchasingGuidance:text('purchasing_guidance'),guidanceUpdatedAt:text('guidance_updated_at'),resolutionStatus:text('resolution_status').notNull().default('pending'),resolutionNote:text('resolution_note'),resolutionBy:text('resolution_by'),resolutionUpdatedAt:text('resolution_updated_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),completedAt:text('completed_at'),hasDivergence:integer('has_divergence'),divergenceReason:text('divergence_reason'),purchasingNotified:integer('purchasing_notified')},t=>[index('invoices_store_created').on(t.storeId,t.createdAt)]);
export const purchasingMessages=sqliteTable('purchasing_messages',{id:text('id').primaryKey(),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),storeId:text('store_id').notNull().references(()=>stores.id),senderRole:text('sender_role').notNull(),senderEmail:text('sender_email').notNull(),senderName:text('sender_name').notNull().default(''),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('purchasing_messages_invoice_date').on(t.invoiceId,t.createdAt),index('purchasing_messages_store_date').on(t.storeId,t.createdAt)]);
export const purchasingReads=sqliteTable('purchasing_reads',{viewerKey:text('viewer_key').notNull(),seenAt:text('seen_at').notNull()},t=>[uniqueIndex('purchasing_reads_viewer').on(t.viewerKey)]);
export const invoiceImportKeys=sqliteTable('invoice_import_keys',{storeId:text('store_id').notNull().references(()=>stores.id),accessKey:text('access_key').notNull(),invoiceId:text('invoice_id').notNull()},t=>[uniqueIndex('invoice_import_keys_store_key').on(t.storeId,t.accessKey)]);
export const deletedInvoices=sqliteTable('deleted_invoices',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),number:text('number').notNull(),supplier:text('supplier').notNull(),checkerName:text('checker_name').notNull(),originalCreatedAt:text('original_created_at').notNull(),completedAt:text('completed_at'),itemCount:integer('item_count').notNull(),deletedBy:text('deleted_by').notNull(),deletedByEmail:text('deleted_by_email').notNull(),reason:text('reason').notNull(),deletedAt:text('deleted_at').notNull()},t=>[index('deleted_invoices_store_date').on(t.storeId,t.deletedAt)]);
export const invoiceItems=sqliteTable('invoice_items',{id:text('id').primaryKey(),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),description:text('description').notNull(),code:text('code').notNull(),tribCode:text('trib_code').notNull(),sku:text('sku').notNull(),unit:text('unit').notNull(),expected:real('expected').notNull(),counted:integer('counted').notNull().default(0)},t=>[index('invoice_items_invoice').on(t.invoiceId)]);
export const unexpected=sqliteTable('unexpected_scans',{id:text('id').primaryKey(),invoiceId:text('invoice_id').notNull().references(()=>invoices.id),code:text('code').notNull(),counted:integer('counted').notNull()},t=>[uniqueIndex('unexpected_invoice_code').on(t.invoiceId,t.code)]);

export const payments=sqliteTable('payments',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),amountCents:integer('amount_cents').notNull(),paidAt:text('paid_at').notNull(),coverageUntil:text('coverage_until').notNull(),method:text('method').notNull(),reference:text('reference').notNull(),note:text('note').notNull(),createdAt:text('created_at').notNull()},t=>[index('payments_store_paid').on(t.storeId,t.paidAt)]);
export const nativeAccounts=sqliteTable('native_accounts',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),email:text('email').notNull(),name:text('name').notNull().default(''),role:text('role').notNull().default('manager'),passwordHash:text('password_hash').notNull(),passwordSalt:text('password_salt').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('native_accounts_email').on(t.email),index('native_accounts_store').on(t.storeId)]);
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull().references(()=>nativeAccounts.id),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('auth_sessions_account').on(t.accountId)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),windowStart:text('window_start').notNull()});
export const passwordResetTokens=sqliteTable('password_reset_tokens',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull().references(()=>nativeAccounts.id),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('password_reset_account').on(t.accountId)]);
export const emailSettings=sqliteTable('email_settings',{id:text('id').primaryKey(),apiKeyCipher:text('api_key_cipher').notNull(),sender:text('sender').notNull(),updatedAt:text('updated_at').notNull()});

export const billingSettings=sqliteTable('billing_settings',{id:text('id').primaryKey(),provider:text('provider').notNull(),updatedAt:text('updated_at').notNull()});

export const mpTestSubscriptions=sqliteTable('mp_test_subscriptions',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),payerEmail:text('payer_email').notNull(),providerId:text('provider_id').notNull(),status:text('status').notNull(),checkoutUrl:text('checkout_url').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('mp_test_subscriptions_provider').on(t.providerId),index('mp_test_subscriptions_store').on(t.storeId)]);

export const mpTestConfig=sqliteTable('mp_test_config',{id:text('id').primaryKey(),sellerId:text('seller_id').notNull(),tokenCipher:text('token_cipher').notNull(),webhookCipher:text('webhook_cipher').notNull().default(''),updatedAt:text('updated_at').notNull()});

export const mpLiveConfig=sqliteTable('mp_live_config',{id:text('id').primaryKey(),tokenCipher:text('token_cipher').notNull(),webhookCipher:text('webhook_cipher').notNull(),enabled:integer('enabled').notNull().default(0),priceCents:integer('price_cents').notNull().default(4999),updatedAt:text('updated_at').notNull()});
export const mpLiveSubscriptions=sqliteTable('mp_live_subscriptions',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),providerId:text('provider_id').notNull(),status:text('status').notNull(),checkoutUrl:text('checkout_url').notNull(),priceCents:integer('price_cents').notNull().default(4999),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('mp_live_subscriptions_provider').on(t.providerId),index('mp_live_subscriptions_store').on(t.storeId)]);
export const mpLivePayments=sqliteTable('mp_live_payments',{paymentId:text('payment_id').primaryKey(),subscriptionId:text('subscription_id').notNull().references(()=>mpLiveSubscriptions.id),storeId:text('store_id').notNull().references(()=>stores.id),paidAt:text('paid_at').notNull(),amountCents:integer('amount_cents').notNull()},t=>[index('mp_live_payments_store').on(t.storeId)]);

export const purchasingChanges=sqliteTable('purchasing_changes',{id:text('id').primaryKey(),storeId:text('store_id').notNull().references(()=>stores.id),invoiceId:text('invoice_id').notNull(),menu:text('menu').notNull(),createdAt:text('created_at').notNull()},t=>[index('purchasing_changes_store_menu_date').on(t.storeId,t.menu,t.createdAt)]);

export const buyerStores=sqliteTable('buyer_stores',{accountId:text('account_id').notNull().references(()=>nativeAccounts.id),storeId:text('store_id').notNull().references(()=>stores.id),status:text('status').notNull().default('pending'),permission:text('permission').notNull().default('operate'),invitedBy:text('invited_by').notNull(),createdAt:text('created_at').notNull(),acceptedAt:text('accepted_at')},t=>[uniqueIndex('buyer_stores_account_store').on(t.accountId,t.storeId),index('buyer_stores_store').on(t.storeId)]);

export const conferenceLocks=sqliteTable('conference_locks',{invoiceId:text('invoice_id').primaryKey().references(()=>invoices.id),storeId:text('store_id').notNull().references(()=>stores.id),holderToken:text('holder_token').notNull(),holderName:text('holder_name').notNull(),expiresAt:text('expires_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('conference_locks_store').on(t.storeId)]);
