'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/client-api';
import {Button} from '@/components/ui/button';
type Note={id:string;number:string;supplier:string;checkerName:string;createdAt:string;completedAt:string|null;hasDivergence:number|null;purchasingGuidance:string|null;guidanceUpdatedAt:string|null};
type Group='waiting'|'progress'|'entry'|'guidance';
type Priorities={storeName:string;counts:Record<Group,number>;waiting:Note[];progress:Note[];entry:Note[];guidance:Note[]};
const labels:Record<Group,string>={waiting:'Aguardando conferência',progress:'Conferências em andamento',entry:'Aguardando entrada',guidance:'Novas orientações de Compras'};
export default function StorePriorities({storeName,onOpen,onNew,onHistory}:{storeName:string;onOpen:(id:string,focusScan?:boolean)=>Promise<void>;onNew:()=>void;onHistory:()=>void}){
 const [data,setData]=useState<Priorities|null>(null),[error,setError]=useState(''),[opening,setOpening]=useState<string|null>(null);const refs=useRef<Partial<Record<Group,HTMLElement|null>>>({});
 useEffect(()=>{let active=true,pending=false;async function refresh(){if(pending||document.visibilityState!=='visible')return;pending=true;try{const next=await api('/api/priorities');if(active){setData(next);setError('')}}catch(e){if(active)setError((e as Error).message)}finally{pending=false}}refresh();const timer=setInterval(refresh,10000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh)}},[]);
 async function open(id:string,focusScan=true){setOpening(id);try{await onOpen(id,focusScan)}catch(e){setError((e as Error).message)}finally{setOpening(null)}}
 return <><div className="pagehead"><div><div className="eyebrow">PRIORIDADES DA LOJA</div><h1>{storeName}</h1><p>Veja o que precisa de atenção e continue a conferência da nota.</p></div><Button onClick={onNew}>Nova conferência</Button></div>{error&&<p className="notice bad" role="alert">{error}</p>}{!data?<p role="status">Carregando prioridades...</p>:<><div className="metrics priority-metrics">{(Object.keys(labels) as Group[]).map(group=><button className="metric" key={group} onClick={()=>refs.current[group]?.scrollIntoView({behavior:'smooth',block:'start'})}><span>{labels[group]}</span><b>{data.counts[group]}</b></button>)}</div><div className="priority-grid">{(['guidance','waiting','progress','entry'] as Group[]).map(group=><section className="panel reports-panel priority-group" key={group} ref={element=>{refs.current[group]=element}}><h2>{labels[group]}</h2><p>{group==='guidance'?'Abra a nota para ver a orientação e confirmar a leitura.':group==='entry'?'Conferidas, aguardando a confirmação de entrada por Compras.':'As notas mais antigas aparecem primeiro.'}</p>{data[group].length?data[group].map(note=><article className={'priority-note '+(group==='guidance'?'priority-guidance':'')} key={note.id}><div><b className={note.hasDivergence===1?'invoice-divergent':undefined}>NF-e {note.number}</b>{group==='guidance'&&<span className="priority-new">Nova orientação</span>}{(group==='waiting'||group==='progress')&&<span className="priority-age">Há {Math.max(0,Math.floor((Date.now()-Date.parse(note.createdAt))/86400000))} dia(s)</span>}<small>{note.supplier||'Fornecedor não informado'} · Recebida em {new Date(note.createdAt).toLocaleString('pt-BR')}</small>{note.checkerName&&<small>Conferente: {note.checkerName}</small>}{group==='guidance'&&<p>{note.purchasingGuidance}</p>}</div><Button variant="outline" disabled={!!opening} onClick={()=>open(note.id,group!=='guidance')}>{opening===note.id?'Abrindo...':group==='guidance'?'Ver orientação':group==='progress'?'Continuar':'Abrir nota'}</Button></article>):<p>Nenhuma nota nesta situação.</p>}{data.counts[group]>20&&<p>Exibindo as 20 primeiras de {data.counts[group]} notas. <button className="priority-history-link" onClick={onHistory}>Consultar histórico</button></p>}</section>)}</div></>}</>
}
